### ISSUE TITLE
EventStoreClient throws NullReferenceException when acknowledging event in PersistentSubscription

### ISSUE THREAD

**Issue by andrii-litvinov** [EventStore/EventStoreDB-Client-Dotnet-Legacy#43]
Hi there,

I have encountered quite unexpected hard to reproduce `NullReferenceException` with PersistentSubscription that causes process crash. It happens when I use `async` `eventAppeared` and `bufferSize` greater than `1` (which opens for parallel processing of messages) and manual message acknowledgement.

If EventStore goes down (or unavailable for any reason) after `eventAppeared` action was invoked but before I Nacked message I get `NullReferenceException`. Even thought it does not happen on every try it happens more often than I wanted it to :).

I have created a test to reproduce this issue:
```csharp
[Test, Explicit]
public async Task ShouldNotThrowExceptionOnNack()
{
    var stopwatch = Stopwatch.StartNew();
    var connection = EventStoreConnection.Create("ConnectTo=tcp://admin:changeit@localhost:1113");
    await connection.ConnectAsync();

    using (connection)
    {
        // Given
        var count = 0;
        var stream = "SubscriptionStream" + Guid.NewGuid();
        const string groupName = "group";
        await connection.CreatePersistentSubscriptionAsync(stream, groupName, PersistentSubscriptionSettings.Create(), null);

        await connection.ConnectToPersistentSubscriptionAsync(stream, groupName, async (subscription, message) =>
        {
            await Task.Delay(TimeSpan.FromMilliseconds(5));
            try
            {
                if (Interlocked.Increment(ref count) == 1)
                {
                    Process.GetProcessesByName("EventStore.ClusterNode").First().Kill();
                }

                subscription.Fail(message, PersistentSubscriptionNakEventAction.Skip, "Retry");
            }
            catch (Exception e)
            {
                Console.WriteLine("In catch:  {0}.", stopwatch.Elapsed);
                Console.WriteLine(e);
            }
        }, null, bufferSize: 10, autoAck: false);

        var events = Enumerable.Range(0, 10).Select(i => new EventData(Guid.NewGuid(), "Event", false, null, null));
        await connection.AppendToStreamAsync(stream, ExpectedVersion.Any, events);

        Console.WriteLine("In assert: {0}.", stopwatch.Elapsed);
        // Does not reproduce when await is uncommented.
        //await Task.Delay(TimeSpan.FromMilliseconds(1000));
        Thread.Sleep(1000);
        Assert.Fail();
    }
}
```

It should output exception below:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at EventStore.ClientAPI.ClientOperations.SubscriptionOperation`1.EnqueueSend(TcpPackage package)
   at EventStore.ClientAPI.ClientOperations.ConnectToPersistentSubscriptionOperation.NotifyEventsFailed(Guid[] processedEvents, PersistentSubscriptionNakEventAction action, String reason)
   at EventStore.ClientAPI.EventStorePersistentSubscriptionBase.Fail(ResolvedEvent event, PersistentSubscriptionNakEventAction action, String reason)
   at ESTest.PersistentSubscriptionBug.<>c__DisplayClass0_0.<<ShouldNotThrowExceptionOnNack>b__0>d.MoveNext() in C:\Users\andri\documents\visual studio 2015\Projects\ESTest\Class1.cs:line 38
```

If that is expected behavior how should I handle such cased in persistent subscription handler? I already do try to reconnect in `subscriptionDropped` action.

And I am also curious why I cannot reproduce it when use `await Task.Delay` instead of `Thread.Sleep`? Do you do some magic there with async code?

Cheers,
Andrii

**Comment by ylorph** [comment]
Closing .
Please reopen if this happens again .
